mylist = []
print(mylist, type(mylist))
mylist.append('코알라')
print(mylist)
mylist.append('순록')
mylist.append('닭')
print(mylist)
mylist.insert(0, '다람쥐')
print(mylist)
mylist.append('고양이')
mylist.append('햄스터')
print(mylist)
print(mylist[3])
del mylist[3]
print(mylist)
print(mylist[1:4])
mylist.sort()
print(mylist)
print(mylist.count('다람쥐'))
print(len(mylist))
print(len('안녕, 친구들~'))
